### ISSUE TITLE
Typo in UI: 2x "Followers" an no "Following"

### ISSUE THREAD

**Issue by sorenpeter** [jointwt/goryon#82] opened 2021-01-19 21:12 UTC
In the Setting panel there is two time "Followers". I guess one of them is mean to be "Following"

![Screenshot_20210119-220847](https://user-images.githubusercontent.com/8458421/105093508-257c3c00-5aa3-11eb-89f9-51b5cb43f83b.png)

**Comment by prologic** [comment] 2021-01-19 23:29
Duplicate of #80

**Closed by prologic** 2021-01-19 23:29 UTC
